################################################################################
# Copyrights Â© 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
- sections:
    - title: Getting Started
      link: docs/getting-started.md
      open: true
- sections:
    - title: API Reference
      link:
      open: true
      sections:
        - title: Account Management
          sections:
            - title: Block-Unblock Account
              link: docs/APIs/Account-Management/Block-Account.md
            - title: Inquire Account Balances
              link: docs/APIs/Account-Management/account-balances.md
            - title: Inquire Account Details
              link: docs/APIs/Account-Management/account-details.md
            - title: List Billed Transactions
              link: docs/APIs/Account-Management/List-billed-Transactions.md
            - title: List Unbilled Transactions
              link: docs/APIs/Account-Management/List-unbilled-Transactions.md
            - title: List Outstanding Authorizations
              link: docs/APIs/Account-Management/List-Outstanding-Authorizations.md
            - title: Inquire Direct Debit
              link: docs/APIs/Account-Management/Direct-Debit-inq.md
            - title: Update Credit Limit
              link: docs/APIs/Account-Management/Credit-Limit-upd.md              
            - title: Update Account Direct Debit
              link: docs/APIs/Account-Management/Direct-Debit-upd.md
            - title: Update Temporary Credit Limit
              link: docs/APIs/Account-Management/Temp-Credit-Limit-upd.md
            - title: Update Account Charge-Off 
              link: docs/APIs/Account-Management/Update-Account-Charge-Off.md
            - title: Inquire Statement 
              link: docs/APIs/Account-Management/Inquire-Statement.md
            - title: Update Pricing Control  
              link: docs/APIs/Account-Management/Update-Pricing-Control.md              
            - title: Monetary Action
              link: docs/APIs/Account-Management/Monetary-Action.md   
            - title: Update Waive Fee
              link: docs/APIs/Account-Management/Update-Waive-Fee.md   
            - title: Board Account
              link: docs/APIs/Account-Management/Board-Account.md                
        - title: Card Management
          sections:
            - title: Activate Card
              link: docs/APIs/Card-Management/Activate-Card.md
            - title: Block-Unblock Card
              link: docs/APIs/Card-Management/Block-Card.md
            - title: Update Card Type
              link: docs/APIs/Card-Management/CardType-Update.md
            - title: Validate CVV2 
              link: docs/APIs/Card-Management/CVV2-Validation.md
            - title: Fetch Clear PAN from Token
              link: docs/APIs/Card-Management/Fetch-Clear-PAN-from-Token.md
            - title: Transfer Lost Stolen Card
              link: docs/APIs/Card-Management/Lost-Stolen-Card-Transfer.md
            - title: Change PIN
              link: docs/APIs/Card-Management/PIN-Block-Change.md
            - title: Update Spend Limit
              link: docs/APIs/Card-Management/Spend-limit-Updates.md
            - title: Inquire Card
              link: docs/APIs/Card-Management/Inquire-Card.md
            - title: Update Card Controls
              link: docs/APIs/Card-Management/Update-Card-Controls.md    
            - title: Inquire Card Controls
              link: docs/APIs/Card-Management/Inquire-Card-Controls.md                   
        - title: Customer Management
          sections:
            - title: Inquire Customer Demographic
              link: docs/APIs/Customer-Management/Customer-Demographic-Inquiry.md
            - title: Update Customer Demographic
              link: docs/APIs/Customer-Management/Customer-Demographic-Update.md
            - title: List Customers' Accounts
              link: docs/APIs/Customer-Management/List-Customers-Accounts.md
            - title: List Customers' Cards
              link: docs/APIs/Customer-Management/List-Customers-Cards.md
            - title: Board Customer
              link: docs/APIs/Customer-Management/Board-Customer.md
            - title: Search Customer
              link: docs/APIs/Customer-Management/Search-Customer.md